version: "3.4"

services:
  db_dev:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: jwp_dev
      POSTGRES_PASSWORD: jwp_dev
    volumes:
      - ./docker/postgres_dev/data:/var/lib/postgresql/data:rw
    ports:
      - "8826:5432"

  db_test:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: jwp_test
      POSTGRES_PASSWORD: jwp_test
    volumes:
      - ./docker/postgres_test/data:/var/lib/postgresql/data:rw
    ports:
      - "8827:5432"      